# Generated by Django 6.1.1 on 2026-09-10 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avito_app', '0004_alter_review_stars_reviewcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_price',
            new_name='price',
        ),
    ]
